# Generated by Django 4.0.4 on 2022-04-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsi_belsi_auth', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile_image.jpg', upload_to='profiles'),
        ),
    ]
