# Generated by Django 4.0.4 on 2022-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsi_belsi_auth', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='elsibelsihandmadeuser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
