# Generated by Django 4.0.4 on 2022-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsi_belsi_auth', '0006_elsibelsihandmadeuser_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linked_in_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
