# Generated by Django 4.0.4 on 2022-04-19 09:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('prd_category', models.CharField(choices=[('Cards', 'Cards'), ('Jewelry', 'Jewelry'), ('Paintings', 'Paintings'), ('Wooden Toys', 'Wooden Toys')], default='Cards', max_length=20)),
                ('prd_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('prd_image', models.ImageField(upload_to='products')),
                ('prd_date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('prd_date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Date Updated')),
                ('prd_price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('favourites', models.ManyToManyField(blank=True, related_name='product_favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsi_belsi_products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
