# Generated by Django 4.0.4 on 2022-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsi_belsi_products', '0002_alter_product_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_image',
            field=models.ImageField(blank=True, default='default_product_image.png', upload_to='products'),
        ),
    ]
