# Generated by Django 4.0.4 on 2022-04-19 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elsi_belsi_products', '0003_alter_product_prd_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prd_user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
