# Generated by Django 4.0.4 on 2022-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsi_belsi_products', '0004_product_prd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
