# Generated by Django 4.0.4 on 2022-04-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsi_belsi_products', '0006_remove_product_favourites_product_favorites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prd_likes',
            new_name='likes',
        ),
    ]
