# Generated by Django 4.0.4 on 2022-04-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsi_belsi_products', '0007_rename_prd_likes_product_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
