# Generated by Django 4.0.4 on 2022-04-25 11:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsi_belsi_products', '0015_alter_product_favorites_alter_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prd_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='prd_date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
    ]
